### PR TITLE
[Draft] add editable plots

### PR DESCRIPTION
**Pull request by PabloRuizCuevas**
Draft code for #34

### CODE REVIEW

**Comment by olavolav** [comment]
Thank you for this! Testing it out, will update

**Comment by PabloRuizCuevas** [comment]
Hi @olavolav did you have any thoughts on this topic? this implementation was not directly intended to be merged, but if you have any suggestion or direction on how to implement this, I would happily help.

**Comment by olavolav** [comment]
@PabloRuizCuevas Yes I did, and thank you for the follow-up. I have some diffs and will publish later or tomorrow that are essentially your idea in a slightly different form.

**Comment by olavolav** [comment]
See comments in #34, closing for now

**Pull request closed without merging**
